-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Catppuccin Mocha palette

local base = "rgb(1e1e2e)"

local mantle = "rgb(181825)"

local crust = "rgb(11111b)"

local text = "rgb(cdd6f4)"

local subtext0 = "rgb(a6adc8)"

local subtext1 = "rgb(bac2de)"

local surface0 = "rgb(313244)"

local surface1 = "rgb(45475a)"

local surface2 = "rgb(585b70)"

local overlay0 = "rgb(6c7086)"

local overlay1 = "rgb(7f849c)"

local overlay2 = "rgb(9399b2)"

local blue = "rgb(89b4fa)"

local lavender = "rgb(b4befe)"

local sapphire = "rgb(74c7ec)"

local sky = "rgb(89dceb)"

local teal = "rgb(94e2d5)"

local green = "rgb(a6e3a1)"

local yellow = "rgb(f9e2af)"

local peach = "rgb(fab387)"

local maroon = "rgb(eba0ac)"

local red = "rgb(f38ba8)"

local mauve = "rgb(cba6f7)"

local pink = "rgb(f5c2e7)"

local flamingo = "rgb(f2cdcd)"

local rosewater = "rgb(f5e0dc)"
