# --- NAMING SETUP ---

# Binary Name
$terminal = kitty
$editor = micro
$fileManager = thunar

# Desktop Name
$browserDesktop = com.brave.Browser.desktop
$fileManagerDesktop = thunar.desktop
$editorDesktop = dev.zed.Zed.desktop
$imageViewDesktop = org.gnome.Loupe.desktop
$videoPlayerDesktop = org.videolan.VLC.desktop
$pdfViewerDesktop = org.gnome.Papers.desktop
$archiveDesktop = io.github.peazip.PeaZip.desktop
$discordDesktop = vesktop.desktop
$pcapDesktop = org.wireshark.Wireshark.desktop

# --- ENV VARIABLES SETUP ---

env = TERMINAL,$terminal
env = EDITOR,$editor
env = FILEMANAGER,$fileManager
env = BROWSER,$browser

# --- XDG SETUP ---

# Web & Internet
exec-once = xdg-settings set default-web-browser $browserDesktop
exec-once = xdg-mime default $browserDesktop x-scheme-handler/http x-scheme-handler/https text/html application/xhtml+xml
exec-once = xdg-mime default $discordDesktop x-scheme-handler/discord

# Files & System
exec-once = xdg-mime default $fileManagerDesktop inode/directory application/x-gnome-saved-search
exec-once = xdg-mime default $archiveDesktop application/vnd.rar
exec-once = xdg-mime default $pcapDesktop application/vnd.tcpdump.pcap

# Media & Docs
exec-once = xdg-mime default $imageViewDesktop image/jpeg image/png
exec-once = xdg-mime default $videoPlayerDesktop video/mp4
exec-once = xdg-mime default $pdfViewerDesktop application/pdf
exec-once = xdg-mime default $editorDesktop application/json